version: "3.3"


services:
  byte_track_sahi:
    build:
      context: ./byte_track_sahi/
      dockerfile: Dockerfile
    volumes: 
      - "./byte_track_sahi:/byte_track_sahi"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
              
